### ISSUE TITLE
Issue with FluentCounterColumns 

### ISSUE THREAD

**Issue by ghost** [fluentcassandra/fluentcassandra#103]
Hi Nick,

I'm trying to find a way to increment multiple counter columns at once using FluentCounterColumn - it looks like FluentCounterColumns aren't supported in CassandraContext.SaveChanges() yet.

I'd be happy to add this capability to FluentCassandra, but I am having some trouble figuring out where to start inside the FluentCassandra codebase.

Could you please outline the steps for what I would need to do to be able to support FluentCounterColumns inside batch mutations (CassandraContext.SaveChanges()) ?

**Comment by nberardi** [comment]
You should talk with @aaronontheweb he started working on this over the weekend.

**Comment by Aaronontheweb** [comment]
@nberardi Cenk and I are on the same team - unfortunately I don't know the answer to his question either; what we're looking for is some clarification on what we need to do to enable FluentCassandra to support batch mutations with FluentCounterColumns - if you could give us some idea of where we should start that would be tremendously helpful :)

**Comment by nberardi** [comment]
Okay didn't know you were on the same team.  I assume you guys have done the first step and know that you can do this via a batch update.  Assuming that has been done the next logical step is to start here:

https://github.com/managedfusion/fluentcassandra/blob/master/src/Types/CounterColumnType.cs

This is the type that is used for the counter.  Assuming nothing has to change with `FluentColumn` class.  The next thing you will need to do is start with the batch operation.  

https://github.com/managedfusion/fluentcassandra/blob/master/src/Operations/BatchMutate.cs

This readies the collection to be passed to the RPC Thrift interface.  But assuming all that is correct, the majority of the code changes will probably take place in the Helper file that does the actual mapping between Fluent Cassandra objects and Thrift object.

https://github.com/managedfusion/fluentcassandra/blob/master/src/Operations/Helper.cs

Let me know if you have any questions beyond this.  My biggest lack of understanding is how you actually increment a counter column and thus transmit that increment back to the db.

**Comment by ghost** [comment]
When i try to use FluentCounterColumn like below. i am having exception. Either i dont use it correctlly or there is a problem with FluentCounterColumn. 
**What is wrong here ?  How should i be using FluenCounterColum ?**
i would like to send countercolumn updates in one batch.

```
    public void FluentCassandraSolution_Should_Create_Row_And_Increment_Counter2()
    {
        var dashboardAppCf = _db.GetColumnFamily("Dashboard_App_Daily");

        var sessionCounterName = CompositeType.Create<LongType, UTF8Type>(DateTime.UtcNow.ToCassandraColumnNameDateType(), "Sessions");
        dashboardAppCf.InsertCounterColumn(ProjectId, sessionCounterName, 2);

        var row = dashboardAppCf.CreateRecord(ProjectId);
        var col = new FluentCounterColumn(new CassandraColumnSchema() { NameType = dashboardAppCf.GetSchema().ColumnNameType })
        {
            ColumnValue = 1,
            ColumnName = sessionCounterName
        };
        row.Columns.Add(col);

        _db.Attach(row);
        _db.SaveChanges();
    }
```

FluentCassandra.Operations.CassandraOperationException was unhandled by user code
  HResult=-2146233088
  Message=invalid operation for commutative columnfamily Dashboard_App_Daily
  Source=FluentCassandra
  StackTrace:
       at FluentCassandra.CassandraSession.ExecuteOperation[TResult](Operation`1 action, Nullable`1 throwOnError) in c:\Users\cenkayberkin\Documents\Visual Studio 2012\Projects\fluentcassandra\src\CassandraSession.cs:line 197
       at FluentCassandra.CassandraContext.ExecuteOperation[TResult](Operation`1 action, Nullable`1 throwOnError) in c:\Users\cenkayberkin\Documents\Visual Studio 2012\Projects\fluentcassandra\src\CassandraContext.cs:line 386
       at FluentCassandra.CassandraContext.SaveChanges(Boolean atomic) in c:\Users\cenkayberkin\Documents\Visual Studio 2012\Projects\fluentcassandra\src\CassandraContext.cs:line 296
       at MarkedUp.CassandraValidationTests.Simple.CounterColumnFamilyTests.FluentCassandraSolution_Should_Create_Row_And_Increment_Counter2() in c:\Users\cenkayberkin\Documents\Visual Studio 2012\Projects\markedup-api\tests\MarkedUp.CassandraValidationTests\Simple\CounterColumnFamilyTests.cs:line 78
  InnerException: FluentCassandra.Apache.Cassandra.InvalidRequestException
       HResult=-2146233088
       Message=Exception of type 'FluentCassandra.Apache.Cassandra.InvalidRequestException' was thrown.
       Source=FluentCassandra
       Why=invalid operation for commutative columnfamily Dashboard_App_Daily
       StackTrace:
            at FluentCassandra.Apache.Cassandra.Cassandra.Client.recv_batch_mutate() in c:\Users\cenkayberkin\Documents\Visual Studio 2012\Projects\fluentcassandra\src\Apache\Cassandra\Cassandra.cs:line 1640
            at FluentCassandra.Apache.Cassandra.Cassandra.Client.batch_mutate(Dictionary`2 mutation_map, ConsistencyLevel consistency_level) in c:\Users\cenkayberkin\Documents\Visual Studio 2012\Projects\fluentcassandra\src\Apache\Cassandra\Cassandra.cs:line 1601
            at FluentCassandra.Operations.CassandraClientWrapper.batch_mutate(Dictionary`2 mutation_map, ConsistencyLevel consistency_level) in c:\Users\cenkayberkin\Documents\Visual Studio 2012\Projects\fluentcassandra\src\Operations\CassandraClientWrapper.cs:line 127
            at FluentCassandra.Operations.BatchMutate.Execute() in c:\Users\cenkayberkin\Documents\Visual Studio 2012\Projects\fluentcassandra\src\Operations\BatchMutate.cs:line 54
            at FluentCassandra.Operations.Operation`1.TryExecute(TResult& result) in c:\Users\cenkayberkin\Documents\Visual Studio 2012\Projects\fluentcassandra\src\Operations\Operation.cs:line 37
       InnerException: 

![Exception](https://f.cloud.github.com/assets/1924308/56170/00c2bdc2-5b0a-11e2-86a0-a31615d60499.jpg)

**Comment by nberardi** [comment]
I don't really know if `FluentCounterColumn` is the best approach anymore or even if it was implemented correctly.  Personally I have never had a use case for counter columns.  So I am relying on you guys to give guidance.
