### ISSUE TITLE
Tests failing in GuidGeneratorTest fixture

### ISSUE THREAD

**Issue by tjrobinson** [fluentcassandra/fluentcassandra#23]
On the master branch two of the tests are failing:

**FluentCassandra.GuidGeneratorTest.GetDateTimeLocal**

```
System.ArgumentException : The UTC Offset of the local dateTime parameter does not match the offset argument.
Parameter name: offset

at System.DateTimeOffset..ctor(DateTime dateTime, TimeSpan offset)
at FluentCassandra.GuidGenerator.GenerateTimeBasedGuid(DateTime dateTime, Byte[] node) in GuidGenerator.cs: line 95
at FluentCassandra.GuidGenerator.GenerateTimeBasedGuid(DateTime dateTime) in GuidGenerator.cs: line 84
at FluentCassandra.GuidGeneratorTest.GetDateTimeLocal() in GuidGeneratorTest.cs: line 57
```

**FluentCassandra.GuidGeneratorTest.GetDateTimeUnspecified**

```
Expected: 1980-03-14 12:23:42.112
But was:  1980-03-14 11:23:42.112

at NUnit.Framework.Assert.That(Object actual, IResolveConstraint expression, String message, Object[] args)
at FluentCassandra.GuidGeneratorTest.GetDateTimeUnspecified() in GuidGeneratorTest.cs: line 49
```

I will investigate and if I can resolve the problem then I'll submit a fix.

**Comment by tjrobinson** [comment]
It's worth mentioning that I'm running this on a machine in the UK which is in the "(UTC) Dublin, Edinburgh, Lisbon, London" time zone, currently in Daylight Saving Time (UTC +1).

**Comment by nberardi** [comment]
Thank you I will take a look at this.

**Comment by nberardi** [comment]
I had a similar issue just pop up recently.  I need to investigate further.

**Comment by nberardi** [comment]
It appears the DateTime and DateTimeOffset objects don't abide by day light savings time.

**Comment by nberardi** [comment]
This change will go out with the next push to NuGet.  Thank you for submitting this bug.
