### ISSUE TITLE
Multiple CQL Commands Per Request

### ISSUE THREAD

**Issue by nberardi** [fluentcassandra/fluentcassandra#31]
FluentCassandra.Operations.CassandraOperationException was caught
  Message=line 1:1095 mismatched input 'UPDATE' expecting EOF
  Source=FluentCassandra
  StackTrace:
       at FluentCassandra.CassandraSession.ExecuteOperation[TResult](Operation`1 action, Nullable`1 throwOnError)
       at FluentCassandra.CassandraContext.ExecuteOperation[TResult](Operation`1 action, Nullable`1 throwOnError)
       at FluentCassandra.CassandraContext.ExecuteQuery(UTF8Type cqlQuery)
       at GitHub.Cassandra.EventMigration.Program.WriteEvents(Event[] events) in C:\Work\Code\GitHub.Cassandra.EventMigration\GitHub.Cassandra.EventMigration\Program.cs:line 194
  InnerException: Apache.Cassandra.InvalidRequestException
       Message=Exception of type 'Apache.Cassandra.InvalidRequestException' was thrown.
       Source=FluentCassandra
       Why=line 1:1095 mismatched input 'UPDATE' expecting EOF
       StackTrace:
            at Apache.Cassandra.Cassandra.Client.recv_execute_cql_query()
            at Apache.Cassandra.Cassandra.Client.execute_cql_query(Byte[] query, Compression compression)
            at FluentCassandra.Operations.CassandraClientWrapper.execute_cql_query(Byte[] query, Compression compression)
            at FluentCassandra.Operations.ExecuteCqlQuery.Execute()
            at FluentCassandra.Operations.Operation`1.TryExecute(TResult& result)
       InnerException:

**Comment by nberardi** [comment]
This isn't an issue with FluentCassandra.  You need to wrap the statement in BATCH.  See the documentation here http://cassandra.apache.org/doc/cql/CQL.html#BATCH

This is how it would be programmed with FluentCassandra

```
    [Fact]
    public void Test()
    {
        using (var db = new CassandraContext("Testing", "localhost"))
        {
            // arrange
            db.ExecuteNonQuery("CREATE TABLE KellaByte (KEY text PRIMARY KEY) WITH comparator = text AND default_validation = decimal");
            db.ExecuteNonQuery(@"BEGIN BATCH
INSERT INTO KellaByte (KEY, 'MyColumn') VALUES ('Key0', 1000000000000000000)
INSERT INTO KellaByte (KEY, 'MyColumn') VALUES ('Key1', 0.25)
INSERT INTO KellaByte (KEY, 'MyColumn') VALUES ('Key2', 2000000000000.1234)
INSERT INTO KellaByte (KEY, 'MyColumn') VALUES ('Key3', -0.25)
APPLY BATCH;");

            // act
            var actual = db.ExecuteQuery("SELECT * FROM KellaByte");

            // assert
            var results = actual.ToList();
            Assert.Equal(1000000000000000000M, (decimal)results.First(x => x.Key == "Key0")["MyColumn"]);
            Assert.Equal(.25M, (decimal)results.First(x => x.Key == "Key1")["MyColumn"]);
            Assert.Equal(2000000000000.1234M, (decimal)results.First(x => x.Key == "Key2")["MyColumn"]);
            Assert.Equal(-.25M, (decimal)results.First(x => x.Key == "Key3")["MyColumn"]);
        }
    }
```
